question_data = [
{"text": "A slug's blood is green.", "answer": "True"},
{"text": "The loudest animal is the African Elephant.", "answer": "False"},
{"text": "Approximately one quarter of human bones are in the feet.", "answer": "True"},
{"text": "The total surface area of a human lungs is the size of a football pitch.", "answer": "True"},
{"text": "In West Virginia, USA, if you accidentally hit an animal with your car, you are free to take it home to eat.", "answer": "True"},
{"text": "In London, UK, if you happen to die in the House of Parliament, you are entitled to a state funeral.", "answer": "False"},
{"text": "It is illegal to pee in the Ocean in Portugal.", "answer": "True"},
{"text": "You can lead a cow down stairs but not up stairs.", "answer": "False"},
{"text": "Google was originally called 'Backrub'.", "answer": "True"},
{"text": "Buzz Aldrin's mother's maiden name was 'Moon'.", "answer": "True"},
{"text": "No piece of square dry paper can be folded in half more than 7 times.", "answer": "False"},
{"text": "A few ounces of chocolate can to kill a small dog.", "answer": "True"}
]

# https://opentdb.com/ 에서 quiz db 생성할 수 있음. - API - GENERATE API URL
# question_data = [
#     {"category": "Science: Computers", "type": "multiple",
#      "difficulty": "easy",
#      "question": "Which company was established on April 1st, 1976 by Steve Jobs, Steve Wozniak and Ronald Wayne?",
#      "correct_answer": "Apple",
#      "incorrect_answers": ["Microsoft", "Atari", "Commodore"]},
#     {"category": "Science: Computers", "type": "multiple",
#      "difficulty": "easy",
#      "question": "When Gmail first launched, how much storage did it provide for your email?",
#      "correct_answer": "1GB",
#      "incorrect_answers": ["512MB", "5GB", "Unlimited"]},
#     {"category": "Science: Computers", "type": "multiple", "difficulty": "easy",
#      "question": "The programming language &#039;Swift&#039; was created to replace what other programming language?",
#      "correct_answer": "Objective-C", "incorrect_answers": ["C#", "Ruby", "C++"]},
#     {"category": "Science: Computers", "type": "multiple", "difficulty": "easy",
#      "question": "In the programming language Java, which of these keywords would you put on a variable to make sure it doesn&#039;t get modified?",
#      "correct_answer": "Final", "incorrect_answers": ["Static", "Private", "Public"]},
#     {"category": "Science: Computers", "type": "multiple", "difficulty": "easy",
#      "question": "What is the domain name for the country Tuvalu?", "correct_answer": ".tv",
#      "incorrect_answers": [".tu", ".tt", ".tl"]},
#     {"category": "Science: Computers", "type": "boolean", "difficulty": "easy",
#      "question": "Ada Lovelace is often considered the first computer programmer.",
#      "correct_answer": "True", "incorrect_answers": ["False"]},
#     {"category": "Science: Computers", "type": "boolean", "difficulty": "easy",
#      "question": "Time on Computers is measured via the EPOX System.", "correct_answer": "False",
#      "incorrect_answers": ["True"]},
#     {"category": "Science: Computers", "type": "multiple", "difficulty": "easy",
#      "question": "What does LTS stand for in the software market?", "correct_answer": "Long Term Support",
#      "incorrect_answers": ["Long Taco Service", "Ludicrous Transfer Speed", "Ludicrous Turbo Speed"]},
#     {"category": "Science: Computers", "type": "boolean", "difficulty": "easy",
#      "question": "The Windows 7 operating system has six main editions.", "correct_answer": "True",
#      "incorrect_answers": ["False"]},
#     {"category": "Science: Computers", "type": "multiple", "difficulty": "easy",
#      "question": "What language does Node.js use?", "correct_answer": "JavaScript",
#      "incorrect_answers": ["Java", "Java Source", "Joomla Source Code"]}
# ]
